### ISSUE TITLE
图片折叠需求-可以提供一个li折叠即使只有自身，也可以折叠的插件吗？

### ISSUE THREAD

**Issue by masterAllen** [Burgerd4sh/zfolder#1]
谢谢你的插件，终于能实现折叠了。

不过我想请问一下，我想折叠图片，现在每次需要加一个li，然后图片前再加一个子li，有点麻烦。可以提供一个li折叠即使只有自身，也可以折叠的插件吗？

**Comment by Burgerd4sh** [comment]
对于你想要实现的功能我有点不太理解，能否举个样例说明下你目前是如何使用的和你想要实现的效果？

- 关于图片折叠
  我的理解是你实际上只是想要一个图片折叠功能。嗯，我不太清楚图片折叠实现的效果应该是怎样才好。我担心可能如果这个效果实现的不好的话会和li折叠起冲突导致bug。如果你有啥好想法或者在其它软件里见过类似的功能的话举个

- 关于单li条目折叠

  我感觉这个没太必要吧，因为折不折叠高度都是一样的，我还特地筛的如果是单li的话不折叠呢……我确实没想过第一个li就是图片的情况。但是如果有图片折叠的话应该这个就没必要了吧？

- 关于中第一个li的内容即是图片的**bug**

  你提的issue还让我发现了个bug……我设置的折叠按钮是相对li的位置，一般来说如果是文字的话按钮位置是正好适合的。但是如果第一个li是图片的话会导致按钮不在圆点旁边。我下个版本会试着修复。

**Comment by Burgerd4sh** [comment]
你要的图片折叠来了，虽然可能不太优雅但是能用[doge]
等你确认后关闭问题

**Comment by masterAllen** [comment]
太棒了，符合我的需求，谢谢你的插件。另外也对之前长时间没回复说声抱歉，重度拖延患者hhh
